LittlerootTown_ProfessorBirchsLab_MapScripts:: @ 81F9C91
	map_script MAP_SCRIPT_ON_TRANSITION, LittlerootTown_ProfessorBirchsLab_OnTransition
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, LittlerootTown_ProfessorBirchsLab_OnWarp
	map_script MAP_SCRIPT_ON_FRAME_TABLE, LittlerootTown_ProfessorBirchsLab_OnFrame
	.byte 0

LittlerootTown_ProfessorBirchsLab_OnTransition: @ 81F9CA1
	end

LittlerootTown_ProfessorBirchsLab_OnWarp: @ 81F9D06
	.2byte 0

LittlerootTown_ProfessorBirchsLab_OnFrame: @ 81F9DB9
	.2byte 0
