enum CostumesByTrainerType
{
// Main characters
    Red,
    Leaf,
	Ethan,
	Kris,
	Lyra,
	Brendan,
	May,
	Lucas,
	Dawn,
// Professors
	Professor_Oak,
	Professor_Elm,
	Professor_Birch,
	Professor_Rowan,
//Rivals
	Garry_Oak,
	Silver,
	Wally,
	Barry,
//Misc characters
	Daisy_Oak,
	Nurse_Joy,
	Officer_Jenny,
	Eusine,
//Standard Trainers
	Beauty,
	Biker,
	Bird_Keeper,
	Blackbelt,
	Bug_Catcher,
	Burglar,
	Channeler,
	Cooltrainer_M, //Ace trainer in Gen 4 // both DPP and HGSS variation
	Cooltrainer_F,
    Cue_Ball,      //Roughneck in gen 4
	Engineer,      //Similar to Worker in gen 4
	Fisherman,
	Gambler,		//PI in gen 4
	Gentleman,
	Hiker,
	Camper,     //Jr. Trainer M in gen 1
	Picnicker,  //Jr. Trainer F in gen 1
	Juggler,
	Lass,
	Pokemaniac,
	Psychic_M,
	Psychic_F,
	Rocker,    //Not in gen 4
	Sailor,
	Scientist_M,
	Scientist_F,
	Super_Nerd,
	Swimmer_M,
	Swimmer_F,
	Tamer,     //Not in gen 4
	Youngster,
	
	Boarder,
	Firebreather,
	Guitarist,
	Kimono_Girl,
	Medium,
	Police_Officer,
	Pokefan_M,
	Pokefan_F,
	Sage,
	Schoolkid_M,
	Schoolkid_F,
	Skier_M,
	Skier_F,
	Teacher,
	Twins_DPP,
	Twins_HGSS,

	Aroma_Lady,
	Battle_Girl,
	Bug_Maniac,     //not in gen 4
	Collector,
	Dragon_Tamer,
	Expert_M,       //Not in gen 4, aka old couple in gen 3
	Expert_F,       //not in gen 4
	Hex_Maniac,     //not in gen 4
	Interviewer,    //known as Reporter in gen 4
	Cameraman,
	Kindler,        //not in gen 4
	Lady,
	Ninja_Boy,
	Parasol_Lady,
	Pokemon_Breeder_M,
	Pokemon_Breeder_F,
	Pokemon_Ranger_M,
	Pokemon_Ranger_F,
	Rich_Boy,
	Ruin_Maniac,
	Triathlete_M,   //not in gen 4
	Triathlete_F,   //not in gen 4
	Tuber_M,
	Tuber_F,
	Young_Couple_M_1,
	Young_Couple_F_1,
	Young_Couple_M_2,
	Young_Couple_F_2,
	Young_Couple_M_3,
	Young_Couple_F_3,
	
	Artist,
	Clown,
	Cowgirl,    //counterpart to rancher
	Cyclist_M,  //gen 4 triathlete
	Cyclist_F,
	Idol,
	Jogger,
	Pokekid,
	Rancher,
	Socialite,
	Veteran,   //Old man sprite in gen 4, M + F variation in gen 5 onwards
	Waiter,
	Waitress,
	Maid,
//Villanous Teams
	Rocket_Grunt_M,
	Rocket_Grunt_F,
	Rocket_Executive_Archer,
	Rocket_Executive_Ariana,
	Rocket_Executive_Petrel,
	Rocket_Executive_Proton,
	Giovanni,
	Aqua_Grunt_M,
	Aqua_Grunt_F,
	Aqua_Admin_Matt,
	Aqua_Admin_Shelley,
	Aqua_Leader_Archie,
	Magma_Grunt_M,
	Magma_Grunt_F,
	Magma_Admin_Courtney,
	Magma_Admin_Tabitha,
	Magma_Leader_Maxie,
	Galactic_Grunt_M,
	Galactic_Grunt_F,
	Commander_Saturn,
	Commander_Mars,
	Commander_Jupiter,
	Commander_Charon,
	Galactic_Boss_Cyrus,
//Gym Leaders + E4 + Champions
	Brock,
	Misty,
	Lt_Surge,
	Erika,
	Koga,
	Janine,
	Sabrina,
	Blaine,
	Lorelei,
	Bruno,
	Agatha,
	Lance,
	Falkner,
	Bugsey,
	Whitney,
	Morty,
	Chuck,
	Jasmine,
	Pryce,
	Clair,	
	Will,
	Karen,
	Roxanne,
	Brawly,
	Wattson,
	Flannery,
	Norman,
	Winona,
	Tate_and_Liza,
	Wallace,
	Juan,
	Sidney,
	Phoebe,
	Glacia,
	Drake,
	Steven,
	Roark,
	Gardenia,
	Maylene,
	Crasher_Wake,
	Fantina,
	Byron,
	Candice,
	Volkner,
	Aaron,
	Bertha,
	Flint,
	Lucian,
	Cynthia,
};
#define NUMBER_OF_COSTUMES Cynthia